# https://dev.azure.com/openpeerpower

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - requirements.txt
      - requirements_build.txt
      - requirements_tests.txt
pr: none
resources:
  repositories:
    - repository: azure
      type: github
      name: "openpeerpower/ci-azure"
      endpoint: "openpeerpower"

stages:
  - stage: "Wheels"
    jobs:
      - template: templates/azp-job-wheels.yaml@azure
        parameters:
          jobName: "Wheels_38_Alpine312"
          builderVersion: "1.0.2-3.8-alpine3.12"
          builderApk: "build-base;libffi-dev;openssl-dev"
          wheelsRequirement: "requirements_all.txt"
          preBuild:
            - script: |
                cat requirements.txt requirements_build.txt > requirements_all.txt
              displayName: "Prepare requirements"
