name: Wheels

on: workflow_dispatch

jobs:
  build:
    name: Build ${{ matrix.arch }}-python${{ matrix.python }}-alpine${{ matrix.alpine }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]
        alpine: ["3.12"]
        arch: ["aarch64", "armhf", "armv7", "amd64", "i386"]

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2

      - name: Prepare requirements
        run: cat requirements.txt requirements_build.txt > requirements_all.txt

      - name: Build wheels
        uses: openpeerpower/wheels@main
        with:
          tag: ${{ matrix.python }}-alpine${{ matrix.alpine }}
          arch: ${{ matrix.arch }}
          apk: "build-base;libffi-dev;openssl-dev"
          requirements: "requirements_all.txt"
